#ifndef __GEN_H__
#define __GEN_H__

#define GEN_HEADER(__f, __protector, __comment)                 \
do {                                                            \
  fprintf (__f,                                                 \
  "/* This file is autogenerated, do not edit it manually,\n"   \
  "   but edit the `%s' instead.\n"                             \
  "\n"                                                          \
  "   The file was generated on %s\n"                           \
  "\n"                                                          \
  "\n"                                                          \
  "%s.  */\n"                                                   \
  "\n"                                                          \
  "\n"                                                          \
  "#ifndef %s\n"                                                \
  "#define %s\n"                                                \
  "\n"                                                          \
  "\n",                                                         \
  __FILE__, __DATE__, __comment, __protector, __protector);     \
} while (0)

#define GEN_FOOTER(__f, __protector)                            \
  fprintf (__f,                                                 \
  "#endif //%s\n", __protector)


#define GEN_OPEN_FILE(__f, __fname)                             \
do {                                                            \
  if (!(__f = fopen (__fname, "w")))                            \
    {                                                           \
      warn ("failed to open file `%s' for writing", __fname);   \
      return false;                                             \
    }                                                           \
} while (0)


#define GEN_FLUSH_AND_CLOSE(__f)                                \
do {                                                            \
  if (0 != fflush (__f)) err_func (fflush);                     \
  if (0 != fclose (f)) err_func (fclose);                       \
} while (0)



bool gen_types_trav_h (yajl_val traversals, const char *  fname);
bool gen_types_nodetype_h (yajl_val nodes, const char *  fname);
bool gen_traverse_tables_h (yajl_val nodes, yajl_val traversals, const char *  fname);


#endif // __GEN_H__
